BUF_SIZE = 2048
UDP_SIZE = 65536
PACK_IV_LEN = 16
PACK_PAD_LEN = 32

TOKEN_LEN = 20
MAGIC_LEN = 8
MAGIC_LIST_LEN = 1024

STAGE_INIT = -1
STAGE_HANDSHAKE = 0
STAGE_STREAM = 1

CONFIG_FILE = 'configuration.yaml'
USERS_FILE = 'users.yaml'
TRAFFIC_FILE = 'traffic.yaml'

AES_KEY = b'CUSTOM_YOUR_KEY_HERE'

TRAFFIC_SAVE_INTERVAL = 30
